# Generated by Django 4.0.1 on 2022-01-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.ImageField(default='---', max_length=255, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='---', unique=True),
            preserve_default=False,
        ),
    ]
