# Generated by Django 4.0.1 on 2022-01-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_event_cover_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=255),
            preserve_default=False,
        ),
    ]
