# Generated by Django 4.0.1 on 2022-01-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('0', 'Ativo'), ('1', 'Inativo')], default=0, max_length=255),
        ),
    ]
