# Generated by Django 4.0.1 on 2022-01-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('cover', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('author', models.CharField(choices=[('celiojr', 'celiojr')], max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
