# Generated by Django 4.0.1 on 2022-01-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=96, verbose_name='titulo')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('cover', models.ImageField(upload_to='capas', verbose_name='capa')),
                ('authors', models.CharField(max_length=340, verbose_name='autoria')),
                ('publisher', models.CharField(max_length=128, verbose_name='editora')),
                ('release_year', models.IntegerField(verbose_name='ano de publicação')),
                ('isbn', models.DecimalField(decimal_places=0, max_digits=13, verbose_name='ISBN')),
                ('language', models.CharField(choices=[('Português-BR', 'Português-BR'), ('Inglês', 'Inglês'), ('Espanhol', 'Espanhol')], default=('Português-BR', 'Português-BR'), max_length=36, verbose_name='idioma')),
                ('description', models.TextField(verbose_name='descrição')),
            ],
        ),
    ]
