# Generated by Django 4.0.1 on 2022-01-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_remove_book_language_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('L', 'Livro'), ('C', 'Cartilha')], default=0, max_length=255, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(max_length=255, verbose_name='autoria'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=255, verbose_name='editora'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
    ]
